language: node_js
node_js:
  - "node"
  - "10"
  - "8"
  - "6"

# Run the the validate script
script: yarn run validate

# We of course run a build first to generate the build targets
before_deploy: yarn run build

# Using semantic-release, deploy a new version of the library
# We're running multiple node jobs so running on latest Node
# version
deploy:
  provider: script
  script: npx semantic-release
  on:
    node: "node"
