language: node_js
node_js:
  - "node"
  - "10"
  - "8"
  - "6"

# Run the the validate script
script: yarn run validate

# Using semantic-release, deploy a new version of the library
# We're running multiple node jobs so travis-deploy-once ensures
# that it only tries to deploy once. We of course run a build first
# to release the build targets
deploy:
  provider: script
  skip_cleanup: true
  script:
    - yarn run build
    - npx travis-deploy-once "npx semantic-release"
